# Generated by Django 5.1.4 on 2025-06-26 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyRescueSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="紧急地点ID"
                    ),
                ),
                (
                    "nearest_safe_distance",
                    models.FloatField(verbose_name="距安全点最近距离（米）"),
                ),
                ("water_depth", models.FloatField(verbose_name="水淹深度（米）")),
                ("current_people", models.IntegerField(verbose_name="现有人数")),
                ("material_weight", models.IntegerField(verbose_name="物资权重")),
                (
                    "emergency_rescue_people",
                    models.IntegerField(verbose_name="紧急救援人数"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="紧急救援地容量"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_sites",
                        to="basic.pointfeature",
                        verbose_name="位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "紧急救援地点",
                "verbose_name_plural": "紧急救援地点",
            },
        ),
        migrations.CreateModel(
            name="IdlePerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="人员ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "contact",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="联系方式"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idle_persons",
                        to="basic.pointfeature",
                        verbose_name="位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "待救援闲散人员",
                "verbose_name_plural": "待救援闲散人员",
            },
        ),
    ]
